[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

# ================================================================================= #
# ------------------------------------ Project ------------------------------------ #
# ================================================================================= #
[project]
name = "pyml"
dynamic = ["version"]
description = "A machine learning library built from scratch"
requires-python = ">=3.12"
authors = [
    {name = "Sherzod Juraev", email = "juraevsherzod9943@gmail.com"},
]
readme = "README.md"
license = "MIT"
keywords = [
    "education",
    "from-scratch",
    "machine-learning",
]
classifiers = [
    "Development Status :: 4 - Alpha",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Education",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
    "click>=8.5.0",
    "click-help-colors>=0.9.4",
    "numpy>=1.24.0",
    "scipy>=1.10.0",
]

# ================================================================================= #
# --------------------------- Optional Dependencies ------------------------------- #
# ================================================================================= #
[project.optional-dependencies]
dev = [
    "interrogate>=1.7.0",
    "mypy>=1.11",
    "ruff>=0.6.0",
    "pytest>=9.0",
    "pytest-sugar>=1.0",
]
docs = [
    "autodocsumm>=0.2.14",
    "sphinxcontrib-programoutput>=0.18",
    "doc8>=1.0.0",
    "matplotlib>=3.9.0",
    "pydata-sphinx-theme>=0.15.0",
    "rstcheck>=6.0.0",
    "sphinx>=7.0.0",
    "sphinx-autodoc-typehints>=2.2.0",
    "sphinx-copybutton>=0.5.0",
    "sphinx-design>=0.5.0",
    "sphinx-lint>=1.0.0",
    "sphinx-notfound-page>=1.1.0",
    "sphinxext-opengraph>=0.13.0",
    "sphinx-sitemap>=2.6.0",
]
live = [
    "pyml[docs]",
    "sphinx-autobuild>=2025.8.25",
]
all = [
    "pyml[dev]",
    "pyml[live]",
]

# ================================================================================= #
# ------------------------------------- URLs -------------------------------------- #
# ================================================================================= #
[project.urls]
Homepage = "https://github.com/sherzod-juraev/pyml"
Documentation = "https://pyml-edu.readthedocs.io"
Repository = "https://github.com/sherzod-juraev/pyml"

# ================================================================================= #
# ---------------------------------- CLI Scripts ---------------------------------- #
# ================================================================================= #
[project.scripts]
pyml = "pyml._cli.main:cli"

# ================================================================================= #
# ------------------------------------ Setuptools --------------------------------- #
# ================================================================================= #
[tool.setuptools.dynamic]
version = {attr = "pyml.__version__"}

[tool.setuptools.packages.find]
where = [".",]
include = ["pyml", "pyml.*",]
exclude = [
    "tests", "tests.*",
    "docs", "docs.*",
]

[tool.setuptools.package-data]
pyml = ["**/*.pyi",]

# ================================================================================= #
# ------------------------------------- Pytest ------------------------------------ #
# ================================================================================= #
[tool.pytest.ini_options]
minversion = "9.0"
testpaths = ["tests",]
python_files = ["test_*.py", "*_test.py",]
python_classes = ["Test*",]
python_functions = ["test_*",]
addopts = "-v --tb=short --strict-markers --strict-config -p no:warnings"
filterwarnings = ["ignore::UserWarning",]

# ================================================================================= #
# -------------------------------------- Ruff ------------------------------------- #
# ================================================================================= #
[tool.ruff]
target-version = "py312"
line-length = 100
include = [
    "pyml/**/*.py",
    "tests/**/*.py",
]
exclude = [
    "pyml/__pycache__", "pyml/**/__pycache__",
    "tests/__pycache__", "tests/**/__pycache__",
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 88

[tool.ruff.lint]
select = [
    "B", "C4", "D", "E", "F", "I", "N", "UP",
    "RUF012", "RUF022",
    "SIM", "W",
]
ignore = [
    "N803",
    "N806",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "D",
    "N802",
    "SIM",
]

# ================================================================================= #
# -------------------------------------- Mypy ------------------------------------- #
# ================================================================================= #
[tool.mypy]
python_version = "3.12"
strict = true

[[tool.mypy.overrides]]
module = ["scipy.*",]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false

# ================================================================================= #
# ----------------------------------- Interrogate --------------------------------- #
# ================================================================================= #
[tool.interrogate]
fail-under = 100
verbose = 1
quiet = false
whitelist-regex = []
color = true
exclude = [
    "docs",
    "tests",
]
ignore-init-method = false
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = false
ignore-nested-functions = false
ignore-nested-classes = false

# ================================================================================= #
# --------------------------------- Docs Quality Tools ---------------------------- #
# ================================================================================= #
[tool.rstcheck]
ignore_directives = [
    "autoclass", "autofunction",
    "button-link", "button-ref",
    "card",
    "dropdown",
    "grid", "grid-item-card",
    "only",
    "plot",
    "tab-item", "tab-set",
    "toctree",
]
ignore_substitutions = [
    "home_description",
    "nuu_link",
]
ignore_messages = [
    "Unknown target name",
]
ignore_rules = [
    "class",
    "doc",
    "func",
    "meth",
    "ref",
]
report_level = "warning"
ignore_paths = [
    "docs/build/*",
]

[tool.doc8]
max-line-length = 100
ignore = ["D000",]
ignore_paths = [
    "docs/build",
    "docs/source/_static",
]

[tool.sphinx-lint]
max-line-length = 100
exclude = [
    "docs/build",
]
